### ISSUE TITLE
Netbeans 9 bundle exceptions causing pop-up error dialogs

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/os-xtoo#17]
Working on resolving some strange issue that only came up when adding additional modules. Likely can remove some and the problem will go away. I have posted on upstream mailing list, and presently adding debug code to track down what is going wrong. The missing stuff is in the jar next to the class its looking for, so should be able to find. It requires it at build. May need to move messages from Bundle.properties to ```@NbBundle.Message``` annotations. 

Sample exception, there are many and causes File menu to not function, along with missing elements of Edit menu and others.
```
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key paste_formatted_main_menu_item
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:544)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:501)
        at org.netbeans.modules.editor.MainMenuAction$PasteFormattedAction.getMenuItemText(MainMenuAction.java:827)
        at org.netbeans.modules.editor.MainMenuAction.getMenuPresenter(MainMenuAction.java:276)
        at org.netbeans.modules.editor.MainMenuAction.setMenu(MainMenuAction.java:224)
        at org.netbeans.modules.editor.MainMenuAction$1.run(MainMenuAction.java:180)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
....

```

I was getting others so maybe making some progress here not sure, but seems like it.
```
java.util.MissingResourceException: Can't find resource for bundle org.openide.util.NbBundle$PBundle, key CTL_ExportHtmlAction at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:544)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:501)
        at org.openide.util.NbBundle.getMessage(NbBundle.java:617)
        at org.netbeans.modules.editor.ExportHtmlAction.getName(ExportHtmlAction.java:210)
...
```

**Comment by wltjr** [comment]
Resolved! Turns out another [Bundle.properties](https://github.com/apache/incubator-netbeans/blob/master/editor.deprecated.pre65formatting/src/org/netbeans/modules/editor/Bundle.properties) from editor.deprecated.pre65formatting/netbeans-editor-deprecated-pre65formatting. Which neded up in ```org/netbeans/modules/editor```. That prevented Java from finding the correct one from editor/netbeans-editor. Deleting that bundle resovles the issue.
