### ISSUE TITLE
[netbeans] Java Platform Manager - Unable to add Java Platform, errors with one IDE is running on

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/os-xtoo#20]
Various errors with Java Platform Manager

![shot-2018-01-26_12-33-42](https://user-images.githubusercontent.com/12835340/35452651-42619702-0295-11e8-8b14-a425c985764d.jpg)

When adding new Platform
```
java.lang.NullPointerException
	at org.netbeans.modules.java.j2seplatform.wizard.NewJ2SEPlatform.getSDKProperties(NewJ2SEPlatform.java:132)
	at org.netbeans.modules.java.j2seplatform.wizard.NewJ2SEPlatform.run(NewJ2SEPlatform.java:94)
	at org.netbeans.modules.java.j2seplatform.wizard.DetectPanel$WizardPanel$1.run(DetectPanel.java:438)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$FastItem: task failed due to

```

**Comment by wltjr** [comment]
UI is the same with latest snapshot, but I am able to add 10.

**Comment by wltjr** [comment]
Issue remains with 9.0 release, no change since first packaged. Binaries from upstream work. Unsure as to the cause.

**Comment by wltjr** [comment]
The problem with the current/default is the path. As seen in the above screenshot the launcher by default seems to assume ```JAVA_HOME=/usr```. Which is obviously incorrect. Need to get pass a proper path via the startup scripts. Which will fix the issue with the default.

That will likely not resolve the issue with adding new/other JDKs. Still seeking a solution to that problem, or the cause.

**Comment by wltjr** [comment]
![shot-2019-05-24_21-14-17](https://user-images.githubusercontent.com/12835340/81606528-41bacb80-93a1-11ea-87fe-26d5183647b7.jpg)

**Comment by shubham-indalkar** [comment]
> Various errors with Java Platform Manager
> 
> ![shot-2018-01-26_12-33-42](https://user-images.githubusercontent.com/12835340/35452651-42619702-0295-11e8-8b14-a425c985764d.jpg)
> 
> When adding new Platform
> 
> ```
> java.lang.NullPointerException
> 	at org.netbeans.modules.java.j2seplatform.wizard.NewJ2SEPlatform.getSDKProperties(NewJ2SEPlatform.java:132)
> 	at org.netbeans.modules.java.j2seplatform.wizard.NewJ2SEPlatform.run(NewJ2SEPlatform.java:94)
> 	at org.netbeans.modules.java.j2seplatform.wizard.DetectPanel$WizardPanel$1.run(DetectPanel.java:438)
> 	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
> 	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
> 	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
> 	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
> Caused: org.openide.util.RequestProcessor$FastItem: task failed due to
> ```

I'm Having the same problem in NetBeans IDE 14 with openJDK 17.
I cannot set another platform as default and also cannot remove the broken platfrom.

![image](https://user-images.githubusercontent.com/21367218/180234840-d98acb0b-b180-449d-8352-8d304859dab4.png)

how to fix it?

Fixed after doing the following steps.
Uninstalled Open JDK 17 and installed Oracle Java 8
Reinstalled NetBeans
Select path of jdk8 during installation.
Done
