### ISSUE TITLE
[slf4j] Fix odd issue with code that should not have made it into jar?

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/os-xtoo#43]
Odd issue with slf4j, maybe something included in jar that should not be, per exception output

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at aQute.bnd.osgi.Processor.<clinit>(Processor.java:79)
Caused by: java.lang.UnsupportedOperationException: This code should have never made it into slf4j-api.jar
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:63)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:44)
        ... 6 more
```

**Comment by wltjr** [comment]
Resolved by removing code that does not belong in jar. Like all files in [org.slf4j.impl](https://github.com/qos-ch/slf4j/tree/v_1.7.25/slf4j-api/src/main/java/org/slf4j/impl).

Also a missing provider issue per https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/237#issuecomment-344687533. Due to including code that should not be in jar, slf4j thought there was a provider. Which only throws exceptions as it is build time code, stubs, not to be included in jar. Such that you load a provider rather than the stubs. What ever provider is on classpath.
