### ISSUE TITLE
Netbeans does not build nor run under Java 9

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/os-xtoo#7]
Netbeans via this overlay and pieces from tree does not build under Java 9. Work is ongoing but Netbeans horrendous build system is not helping.

**Comment by wltjr** [comment]
Runtime issues are due to eclipse jars in use...
The System Bundle could not be resolved: Missing Constraint: Bundle-RequiredExecutionEnvironment: J2SE-1.5
```
java.lang.RuntimeException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:233)
	at org.eclipse.osgi.framework.internal.core.Framework.launch(Framework.java:656)
	at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.internalInit(EquinoxLauncher.java:69)
	at org.eclipse.osgi.framework.internal.core.EquinoxLauncher.init(EquinoxLauncher.java:37)
	at org.eclipse.osgi.launch.Equinox.init(Equinox.java:178)
	at org.netbeans.modules.netbinox.Netbinox.init(Netbinox.java:84)
	at org.netbeans.core.netigso.Netigso.prepare(Netigso.java:167)
	at org.netbeans.NetigsoHandle.turnOn(NetigsoHandle.java:138)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1353)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start() of bundle org.eclipse.osgi.
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:734)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.resume(InternalSystemBundle.java:225)
	... 17 more
Caused by: java.lang.IllegalStateException: The System Bundle could not be resolved: Missing Constraint: Bundle-RequiredExecutionEnvironment: J2SE-1.5
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.checkSystemState(BaseStorage.java:827)
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.getStateManager(BaseStorage.java:800)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.getState(BaseAdaptor.java:387)
	at org.eclipse.osgi.internal.baseadaptor.BaseStorage.frameworkStart(BaseStorage.java:923)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.frameworkStart(BaseAdaptor.java:250)
	at org.eclipse.osgi.framework.internal.core.SystemBundleActivator.start(SystemBundleActivator.java:60)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	... 19 more
```

**Comment by wltjr** [comment]
Initial work is ongoing to add netbeans 9

**Comment by wltjr** [comment]
No further work is being done on 8.2. I will close this when 9 is at a point I can remove 8.2. Though may do that sooner than later to clean up system and free from java packages in tree :)

**Comment by wltjr** [comment]
Version removed, 9 is semi usable
